 Container aysion_nodejs-db-1  Running
 Container aysion_nodejs-api_02-1  Running
 Container aysion_nodejs-api_01-1  Running
 Container aysion_nodejs-nginx-1  Created
Attaching to api_01-1, api_02-1, db-1, nginx-1
db-1      | 2024-02-09 16:15:27 0 [Note] InnoDB: Starting shutdown...
db-1      | 2024-02-09 16:15:27 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db-1      | 2024-02-09 16:15:27 0 [Note] InnoDB: Buffer pool(s) dump completed at 240209 16:15:27
db-1      | 2024-02-09 16:15:27 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
db-1      | 2024-02-09 16:15:27 0 [Note] InnoDB: Shutdown completed; log sequence number 5544682; transaction id 35875
db-1      | 2024-02-09 16:15:27 0 [Note] mariadbd: Shutdown complete
db-1      | 
db-1 exited with code 0
db-1 exited with code 0
nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
api_01-1  | yarn run v1.22.19
api_02-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
api_02-1  | $ node index.mjs
nginx-1   | 2024/02/09 16:15:31 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/09 16:15:31 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | Server running at 8080
api_02-1  | Server running at 8080
nginx-1   | 2024/02/09 16:15:34 [error] 23#23: *4 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/09 16:15:36 [error] 23#23: *5 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/09 16:15:38 [error] 23#23: *6 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/09 16:15:40 [error] 23#23: *7 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_02-1  | node:internal/process/promises:289
api_02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_02-1  |             ^
api_02-1  | 
api_02-1  | Error: getaddrinfo EAI_AGAIN db
api_02-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_02-1  |   errno: -3001,
api_02-1  |   code: 'EAI_AGAIN',
api_02-1  |   syscall: 'getaddrinfo',
api_02-1  |   hostname: 'db',
api_02-1  |   fatal: true
api_02-1  | }
api_02-1  | 
api_02-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:15:47 [error] 23#23: *8 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_02-1  | error Command failed with exit code 1.
api_02-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_02-1 exited with code 0
api_02-1  | yarn run v1.22.19
api_02-1  | $ node index.mjs
api_02-1  | Server running at 8080
api_01-1  | node:internal/process/promises:289
api_01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_01-1  |             ^
api_01-1  | 
api_01-1  | Error: getaddrinfo EAI_AGAIN db
api_01-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_01-1  |   errno: -3001,
api_01-1  |   code: 'EAI_AGAIN',
api_01-1  |   syscall: 'getaddrinfo',
api_01-1  |   hostname: 'db',
api_01-1  |   fatal: true
api_01-1  | }
api_01-1  | 
api_01-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:15:52 [error] 23#23: *8 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | error Command failed with exit code 1.
api_01-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_01-1 exited with code 0
nginx-1   | 2024/02/09 16:15:54 [error] 23#23: *11 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
api_01-1  | Server running at 8080
nginx-1   | 2024/02/09 16:15:56 [error] 23#23: *12 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_02-1  | node:internal/process/promises:289
api_02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_02-1  |             ^
api_02-1  | 
api_02-1  | Error: getaddrinfo EAI_AGAIN db
api_02-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_02-1  |   errno: -3001,
api_02-1  |   code: 'EAI_AGAIN',
api_02-1  |   syscall: 'getaddrinfo',
api_02-1  |   hostname: 'db',
api_02-1  |   fatal: true
api_02-1  | }
api_02-1  | 
api_02-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:03 [error] 23#23: *13 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_02-1  | error Command failed with exit code 1.
api_02-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_02-1 exited with code 0
api_02-1  | yarn run v1.22.19
api_02-1  | $ node index.mjs
api_02-1  | Server running at 8080
api_01-1  | node:internal/process/promises:289
api_01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_01-1  |             ^
api_01-1  | 
api_01-1  | Error: getaddrinfo EAI_AGAIN db
api_01-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_01-1  |   errno: -3001,
api_01-1  |   code: 'EAI_AGAIN',
api_01-1  |   syscall: 'getaddrinfo',
api_01-1  |   hostname: 'db',
api_01-1  |   fatal: true
api_01-1  | }
api_01-1  | 
api_01-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:08 [error] 23#23: *13 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | error Command failed with exit code 1.
api_01-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_01-1 exited with code 0
nginx-1   | 2024/02/09 16:16:10 [error] 23#23: *16 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
nginx-1   | 2024/02/09 16:16:12 [error] 23#23: *17 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | Server running at 8080
api_02-1  | node:internal/process/promises:289
api_02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_02-1  |             ^
api_02-1  | 
api_02-1  | Error: getaddrinfo EAI_AGAIN db
api_02-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_02-1  |   errno: -3001,
api_02-1  |   code: 'EAI_AGAIN',
api_02-1  |   syscall: 'getaddrinfo',
api_02-1  |   hostname: 'db',
api_02-1  |   fatal: true
api_02-1  | }
api_02-1  | 
api_02-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:19 [error] 23#23: *18 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_02-1  | error Command failed with exit code 1.
api_02-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_02-1 exited with code 0
api_02-1  | yarn run v1.22.19
api_02-1  | $ node index.mjs
api_02-1  | Server running at 8080
api_01-1  | node:internal/process/promises:289
api_01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_01-1  |             ^
api_01-1  | 
api_01-1  | Error: getaddrinfo EAI_AGAIN db
api_01-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_01-1  |   errno: -3001,
api_01-1  |   code: 'EAI_AGAIN',
api_01-1  |   syscall: 'getaddrinfo',
api_01-1  |   hostname: 'db',
api_01-1  |   fatal: true
api_01-1  | }
api_01-1  | 
api_01-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:24 [error] 23#23: *18 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | error Command failed with exit code 1.
api_01-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_01-1 exited with code 0
nginx-1   | 2024/02/09 16:16:26 [error] 23#23: *21 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
nginx-1   | 2024/02/09 16:16:28 [error] 23#23: *22 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | Server running at 8080
api_02-1  | node:internal/process/promises:289
api_02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_02-1  |             ^
api_02-1  | 
api_02-1  | Error: getaddrinfo EAI_AGAIN db
api_02-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_02-1  |   errno: -3001,
api_02-1  |   code: 'EAI_AGAIN',
api_02-1  |   syscall: 'getaddrinfo',
api_02-1  |   hostname: 'db',
api_02-1  |   fatal: true
api_02-1  | }
api_02-1  | 
api_02-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:35 [error] 23#23canceled
tream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_02-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_02-1  | error Command failed with exit code 1.
api_02-1 exited with code 0
api_02-1  | yarn run v1.22.19
api_02-1  | $ node index.mjs
api_02-1  | Server running at 8080
api_01-1  | node:internal/process/promises:289
api_01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_01-1  |             ^
api_01-1  | 
api_01-1  | Error: getaddrinfo EAI_AGAIN db
api_01-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_01-1  |   errno: -3001,
api_01-1  |   code: 'EAI_AGAIN',
api_01-1  |   syscall: 'getaddrinfo',
api_01-1  |   hostname: 'db',
api_01-1  |   fatal: true
api_01-1  | }
api_01-1  | 
api_01-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:40 [error] 23#23: *23 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | error Command failed with exit code 1.
api_01-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_01-1 exited with code 0
nginx-1   | 2024/02/09 16:16:42 [error] 23#23: *26 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
nginx-1   | 2024/02/09 16:16:44 [error] 23#23: *27 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | Server running at 8080
api_02-1  | node:internal/process/promises:289
api_02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_02-1  |             ^
api_02-1  | 
api_02-1  | Error: getaddrinfo EAI_AGAIN db
api_02-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_02-1  |   errno: -3001,
api_02-1  |   code: 'EAI_AGAIN',
api_02-1  |   syscall: 'getaddrinfo',
api_02-1  |   hostname: 'db',
api_02-1  |   fatal: true
api_02-1  | }
api_02-1  | 
api_02-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:51 [error] 23#23: *28 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
api_02-1  | error Command failed with exit code 1.
api_02-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_02-1 exited with code 0
api_02-1  | yarn run v1.22.19
api_02-1  | $ node index.mjs
api_02-1  | Server running at 8080
api_01-1  | node:internal/process/promises:289
api_01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api_01-1  |             ^
api_01-1  | 
api_01-1  | Error: getaddrinfo EAI_AGAIN db
api_01-1  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
api_01-1  |   errno: -3001,
api_01-1  |   code: 'EAI_AGAIN',
api_01-1  |   syscall: 'getaddrinfo',
api_01-1  |   hostname: 'db',
api_01-1  |   fatal: true
api_01-1  | }
api_01-1  | 
api_01-1  | Node.js v20.11.0
nginx-1   | 2024/02/09 16:16:56 [error] 23#23: *28 upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
api_01-1  | error Command failed with exit code 1.
api_01-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_01-1 exited with code 0
nginx-1   | 2024/02/09 16:16:58 [error] 23#23: *31 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_01-1  | yarn run v1.22.19
api_01-1  | $ node index.mjs
api_01-1  | Server running at 8080
nginx-1   | 2024/02/09 16:17:00 [error] 23#23: *32 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api_02-1 exited with code 0
api_01-1 exited with code 0
